### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by Mattsullivan2** [cthomasbabo/WebTech-Project#3]
Technical suggestions: 
1. Your logo is not appearing on the website as an image. I am getting the image not loading the symbol. 
2.  When I click on the "home" header it says 404 page not found. I think the link is not working. 

Content Suggestions: 
1.  The content is very good and the images are great, On the form, I would consider changing the background color to not pink. It pops off the page but is a little hard to type in. 

Really good website and I look forward to seeing the final product

**Comment by cthomasbabo** [comment]
Hey Matt, Thank you for the feedback! I was able to fix my logo issue by using text instead of an image. I also was able to fix the link on the "home" header as well, hopefully that runs smoothly now. I also took your advice and changed the color of those text boxes... I agree pink was too much! Thanks again
